### ISSUE TITLE
[SOLVED] Anybox Alfred Workflow Stuck on “Search for links in Anybox”

### ISSUE THREAD

**Issue by MrMegira** [anyboxhq/anybox-alfred-workflow#10]
Hi,

I’m using the Anybox app with the official Alfred workflow. When I type sd to search for links, the workflow gets stuck at “Search for links in Anybox” (see attached image).
![CleanShot 2024-10-19 at 15 35 02@2x](https://github.com/user-attachments/assets/f51fc837-c427-455e-b480-ab541a083005)

Additionally, I noticed that while this issue occurs, Anybox consumes around 30GB of RAM.

Here’s what I’ve tried so far:

1.	I deleted the workflow, reinstalled it, reset the API key, and added the new one – but the problem persists.
2.	I confirmed that Python 3 is installed on my machine via Terminal (/usr/bin/python3).

I’d appreciate your assistance in resolving this.

Thank you!

**Comment by francisfeng** [comment]
If Anybox is using 30 GB of RAM, it’s acting abnormally. Did you try restarting the app?

**Comment by francisfeng** [comment]
Can you reproduce this issue reliably? I can’t reproduce it.
