### ISSUE TITLE
Feature requirement: Improve search 

### ISSUE THREAD

**Issue by obarlev** [anyboxhq/anybox-alfred-workflow#2]
Seems like the search via Alfred does not search in comments / descriptions (unlike the quick find of AnyBox).
Would you be able to improve the workflow to search in a same way to AnyBox quick find?

**Comment by francisfeng** [comment]
Added in Alfred Workflow 1.1.0: https://github.com/anyboxhq/anybox-alfred-workflow/releases/tag/1.1.0

Anybox for macOS 1.20 is required.
