### ISSUE TITLE
Search for files?

### ISSUE THREAD

**Issue by yinan-c** [anyboxhq/anybox-alfred-workflow#4]
Hi, it seems the workflow only search for links, is it possible to search for files as well?

**Comment by francisfeng** [comment]
It’s technically possible. But you will have to do it yourself as the app is still focusing on links.

https://github.com/anyboxhq/anybox-alfred-workflow/blob/5eb18cc5562137c916c73ce4bf4363ea442c42c6/src/search-links.py#L108

In the Python script of `Search for links in Anybox` action from Alfred, you can add a `type` parameter with value `all`. So the payload will be like:

```python
  payload = {
      'q': q,
      'limit': 30,
      'type': 'all' # 'link' (default) | 'note' | 'image' | 'file' | 'all'
  }
```

With this change, you can search all types of content. If you need to show the file in Finder, you can continue to tweak the action with a few steps.

1. Click the `conditional` object in workflow editor.
2. Click the `Add a new condition` button.
3. Select `matches regex` and paste the regex `^\/Users.*?` in the value field.
4. Connect the condition with a `Reveal File in Finder` action.

<img width="962" alt="conditional object" src="https://github.com/anyboxhq/anybox-alfred-workflow/assets/1040288/19c27162-6c7d-427f-9b8b-c3fd2fc82308">

<img width="809" alt="Alfred workflow action" src="https://github.com/anyboxhq/anybox-alfred-workflow/assets/1040288/586ca4d2-4763-4615-9b91-3ea7e332bc9a">

If you don’t want to maintain a separate version of this workflow, you can copy the action and create a new workflow to just search for files.

**Comment by francisfeng** [comment]
It’s not affecting any functionality. But if you want to remove the error, you can add a condition to make sure `sys.argv` has enough arguments.

```python
import urllib.request
import sys
import os

api_key = os.getenv('api_key')

headers = {'x-api-key': api_key}

if len(sys.argv) >= 3:
    req = urllib.request.Request(
    'http://127.0.0.1:6391/document/' + sys.argv[2], headers=headers, method='PUT')
    urllib.request.urlopen(req)
```

**Comment by yinan-c** [comment]
Thanks, it is really helpful!
