### ISSUE TITLE
sd not working to show links in Anybox

### ISSUE THREAD

**Issue by epetrack1** [anyboxhq/anybox-alfred-workflow#7]
Howdy- Using current versions of Alfred, Anybox. Installed workflow... save commands work in Alfred, but sd-space not showing links. Tried the fix suggested in terminal, but no go (did not offer to install after request). Really would like to use this- please advise, thanks, Emory

emory@Emorys-Mac-Studio ~ % 
emory@Emorys-Mac-Studio ~ % /usr/bin/python3
xcode-select: note: No developer tools were found, requesting install.
If developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.
See `man xcode-select` for more details.
emory@Emorys-Mac-Studio ~ % 
emory@Emorys-Mac-Studio ~ %                 
emory@Emorys-Mac-Studio ~ % xcode-select --install
xcode-select: note: install requested for command line developer tools
emory@Emorys-Mac-Studio ~ % install
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
emory@Emorys-Mac-Studio ~ % 
emory@Emorys-Mac-Studio ~ % sudo xcode-select --reset
Password:
emory@Emorys-Mac-Studio ~ % 
  [Restored Jul 30, 2024 at 3:53:41 PM]
Last login: Tue Jul 30 15:49:51 on ttys000
/Users/emory/.zsh_sessions/83885054-D06C-47DA-A641-828BCE137FCC.session:2: command not found: Saving
emory@Emorys-Mac-Studio ~ %

**Comment by francisfeng** [comment]
You can install Python 3 with command `xcode-select --install`. A alert should pop up when you run this command.

For more details, see https://www.freecodecamp.org/news/install-xcode-command-line-tools/
