### ISSUE TITLE
Include Orion RC as a browser

### ISSUE THREAD

**Issue by paulrudy** [anyboxhq/anybox-alfred-workflow#9]
Would you please consider including Orion RC (the release candidate version of the Orion browser) among the browsers that "save current tab" can work with?

If this helps, from Orion RC's info.plist:

```
<key>CFBundleExecutable</key>
<string>Orion RC</string>
```

Happy to provide other info if needed!

**Comment by francisfeng** [comment]
Sure. But to do that, I need to get the bundle identifier of Orion RC. The value of the key `CFBundleIdentifier` in Info.plist.

**Comment by paulrudy** [comment]
> Sure. But to do that, I need to get the bundle identifier of Orion RC. The value of the key `CFBundleIdentifier` in Info.plist.

Thank you! The value is `com.kagi.kagimacOS.RC`

**Comment by francisfeng** [comment]
I’ve updated the app to support Orion RC. However, since I can’t download the app and give it a try, can you tell me if it’s working for you?

**Comment by paulrudy** [comment]
Works perfectly! Thank you very much for making this change!

**Comment by vprelovac** [comment]
Thanks!
